-- MyDB Database Backup
-- Database: taaza_db
-- Date: 2026-03-10T12:04:26.162281200
-- Generated by MyDB AI-Powered Database Manager

CREATE DATABASE IF NOT EXISTS `taaza_db`;
USE `taaza_db`;

-- Table structure for `admin`
DROP TABLE IF EXISTS `admin`;
CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `email` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `password` varchar(190) NOT NULL,
  `resettoken` varchar(190) NOT NULL,
  `resettokenexpire` date DEFAULT NULL,
  `enable_table_booking` tinyint(4) NOT NULL,
  `enable_menu_page` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `admin`
INSERT INTO `admin` VALUES (1, 'admin@example.com', 'Main Admin', 'bcrypt_hashed_password_placeholder', '', NULL, 1, 1);
INSERT INTO `admin` VALUES (0, 'kundan.m.naik8126@gmail.com', 'Kundan', '$2y$10$BJGJoxTZ/XHwpi/1PE1KAO3nRrZ.PiwZWZosfsuCGL5SBYLEp.m2O', '', NULL, 1, 1);

-- Table structure for `admin_message`
DROP TABLE IF EXISTS `admin_message`;
CREATE TABLE `admin_message` (
  `id` int(11) NOT NULL,
  `message` varchar(5000) NOT NULL,
  `enable_message` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `admin_message`
INSERT INTO `admin_message` VALUES (1, 'HELLO GUYS', 1);

-- Table structure for `contact`
DROP TABLE IF EXISTS `contact`;
CREATE TABLE `contact` (
  `id` int(11) NOT NULL,
  `email` varchar(90) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `contact`
INSERT INTO `contact` VALUES (1, 'new_subscriber@example.com', '2025-10-04 10:00:00.0');
INSERT INTO `contact` VALUES (2, 'interested_customer@example.net', '2025-10-11 15:30:00.0');
INSERT INTO `contact` VALUES (3, 'local_foodie@example.org', '2025-10-19 11:05:00.0');
INSERT INTO `contact` VALUES (4, 'event_planner@example.com', '2025-10-25 09:00:00.0');
INSERT INTO `contact` VALUES (5, 'another_subscriber@example.com', '2025-11-01 17:45:00.0');

-- Table structure for `feedback`
DROP TABLE IF EXISTS `feedback`;
CREATE TABLE `feedback` (
  `feedback_id` int(11) NOT NULL,
  `user_email` varchar(255) NOT NULL,
  `feedback_text` text NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `feedback`
INSERT INTO `feedback` VALUES (1, 'alice@example.com', 'Loved the Margherita Pizza! The crust was perfect. Will be ordering again soon.', '2025-10-05 19:00:00.0');
INSERT INTO `feedback` VALUES (2, 'bob@example.com', 'Service at the table was a little slow last Tuesday, but the food was excellent as always.', '2025-10-08 10:15:30.0');
INSERT INTO `feedback` VALUES (3, 'diana.white@example.net', 'The Filet Mignon was cooked to perfection. A wonderful anniversary dinner, thank you!', '2025-10-11 11:20:00.0');
INSERT INTO `feedback` VALUES (4, 'charlie@example.com', 'Your delivery was very fast. The Grilled Salmon was still hot and delicious.', '2025-10-15 14:00:00.0');
INSERT INTO `feedback` VALUES (5, 'fiona.gold@example.com', 'The new online ordering system is very easy to use. Great job!', '2025-10-20 09:30:15.0');
INSERT INTO `feedback` VALUES (6, 'g.king@example.com', 'The VIP booking for our corporate event was handled flawlessly. The Sky View Lounge is stunning.', '2025-10-23 16:45:00.0');
INSERT INTO `feedback` VALUES (7, 'hannah@example.net', 'The spinach dip was amazing!', '2025-10-28 11:00:00.0');
INSERT INTO `feedback` VALUES (8, 'alice@example.com', 'Tried the Tiramisu this time. It was divine!', '2025-11-01 20:00:00.0');
INSERT INTO `feedback` VALUES (0, 'kundan.m.naik8126@gmail.com', 'very tasty masala dosa', '2025-11-02 23:35:17.0');
INSERT INTO `feedback` VALUES (0, 'kundan.m.naik07@gmail.com', 'my name is rajput mayur, non veg is loooobbbbbeeeeee', '2025-11-07 13:11:18.0');
INSERT INTO `feedback` VALUES (0, 'kundan.m.naik8126@gmail.com', 'very nice dosa. the chutney was delicious', '2025-11-10 18:31:03.0');
INSERT INTO `feedback` VALUES (0, 'kundan.m.naik8126@gmail.com', 'this is my one of the average orders till now. ', '2025-11-17 11:33:27.0');

-- Table structure for `lend_hand`
DROP TABLE IF EXISTS `lend_hand`;
CREATE TABLE `lend_hand` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(90) NOT NULL,
  `amount` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `show_detail` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `lend_hand`
INSERT INTO `lend_hand` VALUES (1, 'Jane Doe', 'jane.doe@example.com', 50, '2025-10-08 14:30:00.0', 1);
INSERT INTO `lend_hand` VALUES (2, 'Anonymous', 'anon@example.com', 20, '2025-10-15 11:00:00.0', 0);
INSERT INTO `lend_hand` VALUES (3, 'Bob Brown', 'bob@example.com', 25, '2025-10-22 18:00:00.0', 1);
INSERT INTO `lend_hand` VALUES (4, 'A Friend', 'friend@example.org', 100, '2025-11-01 12:00:00.0', 0);

-- Table structure for `menu_items`
DROP TABLE IF EXISTS `menu_items`;
CREATE TABLE `menu_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `price` decimal(10,2) NOT NULL,
  `quantity` int(11) NOT NULL DEFAULT 0,
  `available` tinyint(1) NOT NULL DEFAULT 1,
  `image_path` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `menu_items`
INSERT INTO `menu_items` VALUES (19, 'Special Masala Dosa', 'Tasty Masala Dosa', 'Veg', 80.00, 100, true, '1.png');
INSERT INTO `menu_items` VALUES (20, 'Veg Biriyani', 'Biriyani with all veggies and mushrooms', 'Veg', 220.00, 100, true, '2.png');
INSERT INTO `menu_items` VALUES (21, 'Veg Crispy', 'A blend of fried veggies', 'Veg', 150.00, 100, true, '3.png');
INSERT INTO `menu_items` VALUES (22, 'Butter Naan', 'Butter naan with butter', 'Veg', 40.00, 250, true, '4.png');
INSERT INTO `menu_items` VALUES (23, 'Mushroom Curry', 'Mix of Capsicum and Mushroom', 'Veg', 240.00, 100, true, '5.png');
INSERT INTO `menu_items` VALUES (24, 'Shahi Paneer', 'A premium panner with shahi tadka', 'Veg', 280.00, 100, true, '6.png');
INSERT INTO `menu_items` VALUES (25, 'Aloo Paratha', 'Potato Tortilla', 'Veg', 260.00, 200, true, '7.png');
INSERT INTO `menu_items` VALUES (27, 'Garlic Naan', 'Special Garlic naan with buttery twist', 'Veg', 80.00, 100, true, '8.png');
INSERT INTO `menu_items` VALUES (28, 'chicken biryani', 'chicken dum biryani', 'Non-Veg', 220.00, 58, true, '1.jpg');

-- Table structure for `orders`
DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
  `order_id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `address` varchar(200) NOT NULL,
  `item` varchar(30) NOT NULL,
  `quantity` varchar(30) NOT NULL,
  `total_price` varchar(30) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `tr_id` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `orders`
INSERT INTO `orders` VALUES (1, 'Alice Green', 'alice@example.com', '123 Apple St, Los Angeles', 'Margherita Pizza', '1', '18.00', '2025-10-05 18:30:10.0', NULL);
INSERT INTO `orders` VALUES (2, 'Guest User', 'guest1@example.com', '456 Guest Ave, Miami', 'Spaghetti Carbonara', '2', '41.00', '2025-10-06 19:00:22.0', NULL);
INSERT INTO `orders` VALUES (3, 'Bob Brown', 'bob@example.com', '789 Maple Dr, New York', 'Classic Caesar Salad', '1', '12.50', '2025-10-06 20:15:05.0', NULL);
INSERT INTO `orders` VALUES (4, 'Charlie Black', 'charlie@example.com', '101 Pine Ln, Houston', 'Grilled Salmon', '1', '26.00', '2025-10-08 12:05:45.0', NULL);
INSERT INTO `orders` VALUES (5, 'Diana White', 'diana.white@example.net', '202 Birch Rd, Miami', 'Filet Mignon', '2', '76.00', '2025-10-10 20:00:00.0', NULL);
INSERT INTO `orders` VALUES (6, 'Alice Green', 'alice@example.com', '123 Apple St, Los Angeles', 'Classic Tiramisu', '1', '9.50', '2025-10-11 19:30:11.0', NULL);
INSERT INTO `orders` VALUES (7, 'Fiona Gold', 'fiona.gold@example.com', '303 Cedar Pl, San Francisco', 'Mushroom Risotto', '2', '42.00', '2025-10-12 18:45:30.0', NULL);
INSERT INTO `orders` VALUES (8, 'Evan Stone', 'evan.s@example.org', '404 Oak Blvd, Chicago', 'Chicken Parmesan', '1', '22.00', '2025-10-14 17:55:01.0', NULL);
INSERT INTO `orders` VALUES (9, 'Bob Brown', 'bob@example.com', '789 Maple Dr, New York', 'Margherita Pizza', '1', '18.00', '2025-10-15 19:10:00.0', NULL);
INSERT INTO `orders` VALUES (10, 'Hannah Blue', 'hannah@example.net', '505 Spruce Way, Seattle', 'Spinach Artichoke Dip', '1', '14.00', '2025-10-16 16:30:00.0', NULL);
INSERT INTO `orders` VALUES (11, 'Guest User', 'guest2@example.com', '555 Wanderer St, Anytown', 'Bruschetta', '1', '10.00', '2025-10-18 13:00:00.0', NULL);
INSERT INTO `orders` VALUES (12, 'Alice Green', 'alice@example.com', '123 Apple St, Los Angeles', 'Spaghetti Carbonara', '1', '20.50', '2025-10-20 18:00:50.0', NULL);
INSERT INTO `orders` VALUES (13, 'Liam Smith', 'liam@example.org', '606 Peachtree St, Atlanta', 'Filet Mignon', '1', '38.00', '2025-10-21 20:30:00.0', NULL);
INSERT INTO `orders` VALUES (14, 'Mia Wong', 'mia.wong@example.net', '707 Vegas Strip, Las Vegas', 'Chocolate Lava Cake', '2', '22.00', '2025-10-22 21:00:00.0', NULL);
INSERT INTO `orders` VALUES (15, 'Bob Brown', 'bob@example.com', '789 Maple Dr, New York', 'Classic Caesar Salad', '2', '25.00', '2025-10-25 12:15:00.0', NULL);
INSERT INTO `orders` VALUES (16, 'George King', 'g.king@example.com', '808 Cowboy Rd, Dallas', 'Grilled Salmon', '2', '52.00', '2025-10-27 19:45:00.0', NULL);
INSERT INTO `orders` VALUES (17, 'Jane Doe', 'jane.doe@example.com', '909 Desert Rd, Phoenix', 'Mushroom Risotto', '1', '21.00', '2025-10-28 18:20:00.0', NULL);
INSERT INTO `orders` VALUES (18, 'Kenji Watanabe', 'kenji@example.com', '111 Tech Way, San Jose', 'Chicken Parmesan', '1', '22.00', '2025-10-30 19:00:00.0', NULL);
INSERT INTO `orders` VALUES (19, 'Olivia Page', 'olivia.p@example.com', '222 Rose St, Portland', 'Seasonal Special: Pumpkin Pie', '2', '18.00', '2025-11-01 15:00:00.0', NULL);
INSERT INTO `orders` VALUES (20, 'Charlie Black', 'charlie@example.com', '101 Pine Ln, Houston', 'Classic Tiramisu', '1', '9.50', '2025-11-02 12:00:00.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-08 18:57:17.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Biriyani', '1', '220', '2025-11-08 18:57:17.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '6', '900', '2025-11-08 18:57:17.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-08 18:57:21.0', 'tr_afcb1163e4726ef2');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Biriyani', '1', '220.00', '2025-11-08 18:57:21.0', 'tr_afcb1163e4726ef2');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '6', '900.00', '2025-11-08 18:57:21.0', 'tr_afcb1163e4726ef2');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-08 18:58:00.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Biriyani', '1', '220', '2025-11-08 18:58:00.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '6', '900', '2025-11-08 18:58:00.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-08 18:58:02.0', 'tr_202a55da54ef1099');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Biriyani', '1', '220.00', '2025-11-08 18:58:02.0', 'tr_202a55da54ef1099');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '6', '900.00', '2025-11-08 18:58:02.0', 'tr_202a55da54ef1099');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260', '2025-11-08 19:11:05.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220', '2025-11-08 19:11:05.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Garlic Naan', '1', '80', '2025-11-08 19:11:05.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260.00', '2025-11-08 19:11:06.0', 'tr_dba66b755d6f1e1c');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220.00', '2025-11-08 19:11:06.0', 'tr_dba66b755d6f1e1c');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Garlic Naan', '1', '80.00', '2025-11-08 19:11:06.0', 'tr_dba66b755d6f1e1c');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-09 15:20:11.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260', '2025-11-09 15:20:11.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-09 15:20:14.0', 'tr_37fb81fcdec9d49c');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260.00', '2025-11-09 15:20:14.0', 'tr_37fb81fcdec9d49c');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '2', '160', '2025-11-10 12:10:40.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '2', '160.00', '2025-11-10 12:10:44.0', 'tr_b7d5c43712877d90');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '1', '150', '2025-11-10 18:28:49.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Butter Naan', '1', '40', '2025-11-10 18:28:49.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '1', '150.00', '2025-11-10 18:28:53.0', 'tr_ff148ff80333f45e');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Butter Naan', '1', '40.00', '2025-11-10 18:28:53.0', 'tr_ff148ff80333f45e');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260', '2025-11-13 21:00:38.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '1', '150', '2025-11-13 21:00:38.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Aloo Paratha', '1', '260.00', '2025-11-13 21:00:42.0', 'tr_c5efbb371000a784');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Veg Crispy', '1', '150.00', '2025-11-13 21:00:42.0', 'tr_c5efbb371000a784');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-17 11:31:10.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Shahi Paneer', '1', '280', '2025-11-17 11:31:10.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-17 11:31:14.0', 'tr_c254da5a22067e27');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Shahi Paneer', '1', '280.00', '2025-11-17 11:31:14.0', 'tr_c254da5a22067e27');
INSERT INTO `orders` VALUES (0, 'Aditi Somvanshi', 'aduusomvanshi11@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-17 14:50:26.0', NULL);
INSERT INTO `orders` VALUES (0, 'Aditi Somvanshi', 'aduusomvanshi11@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220', '2025-11-17 14:50:26.0', NULL);
INSERT INTO `orders` VALUES (0, 'Aditi Somvanshi', 'aduusomvanshi11@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-17 14:50:29.0', 'tr_2244420dbdc7a27e');
INSERT INTO `orders` VALUES (0, 'Aditi Somvanshi', 'aduusomvanshi11@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220.00', '2025-11-17 14:50:29.0', 'tr_2244420dbdc7a27e');
INSERT INTO `orders` VALUES (0, 'Mustaqeem Shaikh', 'smustaqeem111@gmail.com', 'maharastra aurangabd', 'Veg Crispy', '1', '150', '2025-11-17 15:10:45.0', NULL);
INSERT INTO `orders` VALUES (0, 'Mustaqeem Shaikh', 'smustaqeem111@gmail.com', 'maharastra aurangabd', 'Veg Crispy', '1', '150.00', '2025-11-17 15:10:47.0', 'tr_1335df0b53558eb5');
INSERT INTO `orders` VALUES (0, 'mansi zate', 'mansizate@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80', '2025-11-17 16:39:08.0', NULL);
INSERT INTO `orders` VALUES (0, 'mansi zate', 'mansizate@gmail.com', 'Maharashtra Aurangabad', 'Butter Naan', '1', '40', '2025-11-17 16:39:08.0', NULL);
INSERT INTO `orders` VALUES (0, 'mansi zate', 'mansizate@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '1', '80.00', '2025-11-17 16:39:10.0', 'tr_e4ae9e99abbd8b2d');
INSERT INTO `orders` VALUES (0, 'mansi zate', 'mansizate@gmail.com', 'Maharashtra Aurangabad', 'Butter Naan', '1', '40.00', '2025-11-17 16:39:10.0', 'tr_e4ae9e99abbd8b2d');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '4', '320', '2026-02-13 16:22:35.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '4', '320.00', '2026-02-13 16:22:38.0', 'tr_0b4d5b6035288b03');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '4', '320', '2026-02-13 16:25:03.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220', '2026-02-13 16:25:03.0', NULL);
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'Special Masala Dosa', '4', '320.00', '2026-02-13 16:25:04.0', 'tr_abb9676283560251');
INSERT INTO `orders` VALUES (0, 'KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', 'Maharashtra Aurangabad', 'chicken biryani', '1', '220.00', '2026-02-13 16:25:04.0', 'tr_abb9676283560251');

-- Table structure for `registered_users`
DROP TABLE IF EXISTS `registered_users`;
CREATE TABLE `registered_users` (
  `name` varchar(30) NOT NULL,
  `email` varchar(30) NOT NULL,
  `password` varchar(100) NOT NULL,
  `gender` varchar(18) NOT NULL,
  `state` varchar(30) NOT NULL,
  `district` varchar(30) NOT NULL,
  `verification_code` varchar(225) NOT NULL,
  `is_verified` int(11) NOT NULL DEFAULT 0,
  `resettoken` varchar(255) DEFAULT NULL,
  `resettokenexpire` date DEFAULT NULL,
  `is_vip` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `registered_users`
INSERT INTO `registered_users` VALUES ('Alice Green', 'alice@example.com', 'hashed_pw_placeholder', 'Female', 'California', 'Los Angeles', 'verified_code_1', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Bob Brown', 'bob@example.com', 'hashed_pw_placeholder', 'Male', 'New York', 'New York', 'verified_code_2', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Charlie Black', 'charlie@example.com', 'hashed_pw_placeholder', 'Male', 'Texas', 'Houston', 'verified_code_3', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Diana White', 'diana.white@example.net', 'hashed_pw_placeholder', 'Female', 'Florida', 'Miami', 'verified_code_4', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Evan Stone', 'evan.s@example.org', 'hashed_pw_placeholder', 'Male', 'Illinois', 'Chicago', 'verified_code_5', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Fiona Gold', 'fiona.gold@example.com', 'hashed_pw_placeholder', 'Female', 'California', 'San Francisco', 'verified_code_6', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('George King', 'g.king@example.com', 'hashed_pw_placeholder', 'Male', 'Texas', 'Dallas', 'verified_code_7', 1, NULL, NULL, 1);
INSERT INTO `registered_users` VALUES ('Hannah Blue', 'hannah@example.net', 'hashed_pw_placeholder', 'Female', 'Washington', 'Seattle', 'verified_code_8', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Ian Silver', 'ian@example.org', 'hashed_pw_placeholder', 'Male', 'New York', 'Brooklyn', 'verified_code_9', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Jane Doe', 'jane.doe@example.com', 'hashed_pw_placeholder', 'Female', 'Arizona', 'Phoenix', 'verified_code_10', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Kenji Watanabe', 'kenji@example.com', 'hashed_pw_placeholder', 'Male', 'California', 'San Jose', 'verified_code_11', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Liam Smith', 'liam@example.org', 'hashed_pw_placeholder', 'Male', 'Georgia', 'Atlanta', 'verified_code_12', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Mia Wong', 'mia.wong@example.net', 'hashed_pw_placeholder', 'Female', 'Nevada', 'Las Vegas', 'verified_code_13', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Nate Cole', 'nate@example.com', 'hashed_pw_placeholder', 'Male', 'Colorado', 'Denver', 'unverified_code_14', 0, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Olivia Page', 'olivia.p@example.com', 'hashed_pw_placeholder', 'Female', 'Oregon', 'Portland', 'verified_code_15', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('KUNDAN NAIK', 'kundan@gmail.com', '$2y$10$VkZ/n.zjyH0NFSJRTJNlkuzZL6fg/IJmfnvfwmOuy3U0UPwLvxmpS', 'Male', 'Maharashtra', 'Aurangabad', '152a7a99be56f22a8a674ea94e39961c', 0, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('KUNDAN NAIK', 'kundan.m.naik8126@gmail.com', '$2y$10$btwV6Zc1mcf1Oqb6oRg5CeCorK2FFN26Yke3Q/hb7c5rJU6xJpusS', 'Male', 'Maharashtra', 'Aurangabad', '794c63f82617e617570cf4cdba1db1f8', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('murari naik', 'murarinaik04@gmail.com', '$2y$10$oaVUzXD5p7Gw.rHIP59SwO/X/Ywj9jVjVrs8W6qQ89Gjsq36.WCUu', 'Male', 'Maharashtra', 'Aurangabad', '41271d056d3fdcfffeca52b7fe2c8dfa', 0, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('MAYUR RAJPUT', 'kundan.m.naik07@gmail.com', '$2y$10$PSH0syCaiu6qQsF.DOMQG.sj2dfVIUiNA2hsZMtp2iBu60cBThJQi', 'Male', 'Maharashtra', 'Aurangabad', 'd5d881ccb7043b95eae7b9df888dcafc', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Aditi somvanshi', 'aduusomvanshi11@gmail.com', '$2y$10$1zbKOdF5e1AZJd0GkWJSpOTllMGceEOFCE6nACLkYkDk2MqBqAoRa', 'Female', 'maharastra', 'aurangabd', '5d6625b0db7a99720c1f6e5e31447feb', 1, NULL, NULL, 0);
INSERT INTO `registered_users` VALUES ('Mustaqeem Shaikh', 'smustaqeem111@gmail.com', '$2y$10$frMqNqiWgdGT5QibzDyyi.iCRJvQ3TmDF9A9XnMDOuJRaEY1/7vjG', 'Male', 'maharastra', 'aurangabd', '8f8bc661e34d22424273b22043720b65', 1, NULL, NULL, 0);

-- Table structure for `table_booking_ground`
DROP TABLE IF EXISTS `table_booking_ground`;
CREATE TABLE `table_booking_ground` (
  `id` int(11) NOT NULL,
  `name` varchar(30) NOT NULL,
  `email` varchar(50) NOT NULL,
  `section` varchar(30) NOT NULL,
  `seat` varchar(30) DEFAULT NULL,
  `date` date NOT NULL,
  `time` varchar(50) NOT NULL,
  `payment` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `table_booking_ground`
INSERT INTO `table_booking_ground` VALUES (1, 'Bob Brown', 'bob@example.com', 'Window', '2', '2025-10-07', '19:00', 1);
INSERT INTO `table_booking_ground` VALUES (2, 'Alice Green', 'alice@example.com', 'Patio', '4', '2025-10-09', '20:00', 1);
INSERT INTO `table_booking_ground` VALUES (3, 'Guest Booking', 'guest.booking@example.com', 'Main Floor', '3', '2025-10-10', '18:30', 0);
INSERT INTO `table_booking_ground` VALUES (4, 'Diana White', 'diana.white@example.net', 'Window', '2', '2025-10-12', '19:30', 1);
INSERT INTO `table_booking_ground` VALUES (5, 'Evan Stone', 'evan.s@example.org', 'Bar', '2', '2025-10-15', '21:00', 0);
INSERT INTO `table_booking_ground` VALUES (6, 'Fiona Gold', 'fiona.gold@example.com', 'Patio', '5', '2025-10-17', '18:00', 1);
INSERT INTO `table_booking_ground` VALUES (7, 'Birthday Party', 'party@example.com', 'Main Floor', '8', '2025-10-18', '19:00', 1);
INSERT INTO `table_booking_ground` VALUES (8, 'Hannah Blue', 'hannah@example.net', 'Window', '2', '2025-10-20', '12:00', 0);
INSERT INTO `table_booking_ground` VALUES (9, 'Ian Silver', 'ian@example.org', 'Main Floor', '4', '2025-10-22', '20:30', 1);
INSERT INTO `table_booking_ground` VALUES (10, 'Jane Doe', 'jane.doe@example.com', 'Patio', '2', '2025-10-24', '19:00', 1);
INSERT INTO `table_booking_ground` VALUES (11, 'Kenji Watanabe', 'kenji@example.com', 'Window', '2', '2025-10-26', '18:00', 0);
INSERT INTO `table_booking_ground` VALUES (12, 'Liam Smith', 'liam@example.org', 'Main Floor', '6', '2025-10-28', '19:30', 1);
INSERT INTO `table_booking_ground` VALUES (13, 'Mia Wong', 'mia.wong@example.net', 'Bar', '2', '2025-10-30', '21:30', 0);
INSERT INTO `table_booking_ground` VALUES (14, 'Bob Brown', 'bob@example.com', 'Window', '2', '2025-11-01', '19:00', 1);
INSERT INTO `table_booking_ground` VALUES (15, 'Olivia Page', 'olivia.p@example.com', 'Patio', '4', '2025-11-02', '13:00', 1);
INSERT INTO `table_booking_ground` VALUES (16, 'Upcoming Guest', 'future.guest@example.com', 'Main Floor', '4', '2025-11-05', '20:00', 0);
INSERT INTO `table_booking_ground` VALUES (17, 'Alice Green', 'alice@example.com', 'Window', '2', '2025-11-07', '19:30', 0);
INSERT INTO `table_booking_ground` VALUES (18, 'Charlie Black', 'charlie@example.com', 'Main Floor', '5', '2025-11-08', '18:00', 0);
INSERT INTO `table_booking_ground` VALUES (19, 'Date Night', 'date.night@example.net', 'Window', '2', '2025-11-10', '20:00', 0);
INSERT INTO `table_booking_ground` VALUES (20, 'Fiona Gold', 'fiona.gold@example.com', 'Patio', '4', '2025-11-12', '19:00', 0);

-- Table structure for `table_booking_vip`
DROP TABLE IF EXISTS `table_booking_vip`;
CREATE TABLE `table_booking_vip` (
  `id` int(11) NOT NULL,
  `name` varchar(30) NOT NULL,
  `email` varchar(30) NOT NULL,
  `section` varchar(30) NOT NULL,
  `seat` varchar(30) NOT NULL,
  `decor` varchar(50) NOT NULL,
  `date` date NOT NULL,
  `time` varchar(20) NOT NULL,
  `payment` tinyint(4) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Data for table `table_booking_vip`
INSERT INTO `table_booking_vip` VALUES (1, 'George King', 'g.king@example.com', 'Private Room 1', '8', 'Anniversary', '2025-10-10', '19:00', 1);
INSERT INTO `table_booking_vip` VALUES (2, 'Corporate Event', 'ceo@corp.com', 'Sky View Lounge', '12', 'Business', '2025-10-16', '20:00', 1);
INSERT INTO `table_booking_vip` VALUES (3, 'Sarah Connor', 'sarah.c@example.org', 'Private Room 2', '6', 'Birthday', '2025-10-22', '19:30', 1);
INSERT INTO `table_booking_vip` VALUES (4, 'George King', 'g.king@example.com', 'Sky View Lounge', '4', 'None', '2025-10-29', '20:00', 1);
INSERT INTO `table_booking_vip` VALUES (5, 'Special Occasion', 'special@example.com', 'Private Room 1', '10', 'None', '2025-11-01', '19:00', 1);
INSERT INTO `table_booking_vip` VALUES (6, 'Future VIP', 'future.vip@example.com', 'Private Room 2', '6', 'None', '2025-11-08', '19:30', 0);
INSERT INTO `table_booking_vip` VALUES (7, 'George King', 'g.king@example.com', 'Sky View Lounge', '2', 'None', '2025-11-15', '20:00', 0);

-- Backup completed successfully
